### ISSUE TITLE
Add a way to dynamically choose singular/plural noun form depending on a specified number

### ISSUE THREAD

**Issue by TheBerkin** [TheBerkin/Rant#103]
My current idea for this is to introduce a plural-sensitive subtype specifier using two periods instead of one.

```rant
My name is <name> and I am [n:1;100] <timenoun..s-unit> old.
```

Rant will keep track of the last printed number and check its value when this specific subtype specified is encountered on a query. If the number is one, the subtype falls back to index 0 (or if the user included a regular subtype as well, falls back to that instead). If the number is not one, the term specified by the plural-sensitive subtype is chosen.

The desired behavior is shown by the following outputs:
```
My name is John and I am 43 years old.
My name is Kevin and I am 1 year old.
My name is Jimbob and I am 100 years old.
```

**Comment by Tamschi** [comment]
This seems seriously useful, but the syntax is a little weird. I really can't think of a better alternative though, so pending one I'd like to see this as proposed.
