### ISSUE TITLE
rant.Do(@"<noun>") generates "[Missing Table]" out of the box.

### ISSUE THREAD

**Issue by haggerty-william** [TheBerkin/Rant#104]
Nuget version 2.0.374

var rant = new RantEngine();
var message = rant.Do(@"<noun>");

I find it unusual that out of the box this only produces a "[Missing Table]" string, especially when you claim to have a massive standard dictionary. Does the standard dictionary need to be set up? I looked at your test case(https://github.com/TheBerkin/Rant/blob/master/Rant.Tests/Queries.cs) that is essentially the code above and you didn't configure anything, I also find it hard to believe that the only test case in there is to ensure that "[Missing Table]" != null.

**Comment by haggerty-william** [comment]
Somehow I missed "rant.LoadPackage("Rantionary");" on your website. I wish I could remove all evidence of this issue, but I think my point about the test case is still valid.

**Comment by TheBerkin** [comment]
Glad you sorted out the issue, but you're right that the test case needs to be changed. I don't remember my original rationale behind writing it that way, but I'll make sure to write a better set of test cases once I get back to working on this project.
