### ISSUE TITLE
Problems installing Rant on Unity [SOLVED]

### ISSUE THREAD

**Issue by Santoska** [TheBerkin/Rant#105]
I'm very much a noob when it comes to using external stuff within Unity, so I'm probably missing something obvious.

On the Rantdocs, I saw that installing Rant was very easy; just use the NuGet Package Manager to install Rant in my project. When I try to create a new RantEngine-instance, I get an error stating that the type/namespace RantEngine could not be found. I tried adding 'using Rant' and 'using RantEngine', but to no avail.

The Rantdocs also mentions a RantEngine-Unity.dll, which I cannot find anywhere on the GitHub-repository.

I would very much appreciate if someone could help me out.

I'm using Unity 5.1.1, personal edition in case that matters.

**Comment by cpancake** [comment]
Download the Unity zip from the latest stable AppVeyor build: https://ci.appveyor.com/project/TheBerkin/rant/build/2.0.402/artifacts

See if that solves your problem.

**Comment by Santoska** [comment]
After searching some more on the internet I got it to work! Apparently all I needed to do was paste the unity build .dll file in my Assets folder. Thanks for your help!
