### ISSUE TITLE
Regex syntax in help should be `regex` not <regex> 

### ISSUE THREAD

**Issue by idvorkin** [TheBerkin/rant#116]
I love rant, it's such a cool project.  Minor typo in the docs for regex, which are currently document as 

    ? <regexp>
However the code is expecting 

    ?`<regexp>`

https://github.com/TheBerkin/rant/blob/6f79cc1d3f2e40aa365fee945d7ad82d10c54f26/docs/docs/language/queries/specials/index.html#L1025

**Comment by TheBerkin** [comment]
Thanks for reporting this. I've fixed it and will commit shortly.
