### ISSUE TITLE
"Rantito" .. typo on home page

### ISSUE THREAD

**Issue by burque505** [TheBerkin/rant#122]
From (https://berkin.me/rant/)
"Browse the documentation and familiarize yourself with all aspects of Rant. Engross yourself in every detail of every function, **langauge** feature, and construct available in the library."
As intriguing as it might be to have a LAN gauge in a text processing lib, the language features are even more interesting.  :)
Regards (and many thanks),
burque505

**Comment by TheBerkin** [comment]
Oops! Just fixed it. Thanks!

**Comment by burque505** [comment]
That was fast! Thanks very much for the program.
