### ISSUE TITLE
Link to language files on README.md is broken

### ISSUE THREAD

**Issue by mergenthaler** [TheBerkin/rant#123]
**Describe the bug**
On the **Improve Rant** section on the Readme the link is broken.
This link:  https://github.com/TheBerkin/Rant/blob/dev-3.0/Rant/Localization/en-US.lang
Should probably be: https://github.com/TheBerkin/rant/blob/master/Rant/Localization/en-US.lang
**To Reproduce**
1. Go to Readme.
2. Click on Link

**Comment by TheBerkin** [comment]
Fixed. Thanks!
