### ISSUE TITLE
Java port

### ISSUE THREAD

**Issue by pakoito** [TheBerkin/Rant#16]
C# is still better, but I don't get to choose.

**Comment by sinistersnare** [comment]
What is the status on the portability of Rant? Is it as simple as writing the parser for DSL, and importing the dictionaries, or does Richard complicate things?

**Comment by TheBerkin** [comment]
I don't believe Rant relies on anything in the .NET Framework that would make it difficult or impossible to port.

Richard compiles into AST nodes just like the rest of Rant, I don't think it would be a handicap to porting it apart from making it take more work to do so.

**Comment by sinistersnare** [comment]
Cool, thats good to know. 

Is the AST documented anywhere, or should I just get started digging through the source?

**Comment by TheBerkin** [comment]
We don't have documentation for the AST model, but it's pretty simple in concept. Instead of recursion, it uses iterator methods and a stack.

Check out the `Rant.Engine.Syntax` namespace. The base class is called `RantAction`.
