### ISSUE TITLE
Statements aren't defining variables

### ISSUE THREAD

**Issue by DaaOtt** [TheBerkin/Rant#37]
`````
``b = 10``
`b`
`````

`(Ln 1, Col 1) - Tried to access undefined variable 'b'.`

**Comment by TheBerkin** [comment]
You're using the old math literal syntax. It should look like this:
```rant
`b = 10;`
```
See the [new documentation](http://rantlang.github.io/arithmetic.html) (linked on the old wiki) for information on how math literals work in the most recent version.

**Comment by DaaOtt** [comment]
Oh, didn't see that there was a new wiki. Can you set up an IRC or something so I don't have to make a new issue every time I run into a problem?

**Comment by TheBerkin** [comment]
Sure. Join #rantlang on Freenode.
