### ISSUE TITLE
Proposal For Variable System Overhaul

### ISSUE THREAD

**Issue by cpancake** [TheBerkin/Rant#46]
Right now there are quite a few different types of variables (arithmetic variables, lists, subroutines, carriers...) and they don't play well together. I've talked it over with Berkin and here's what we came up with:
* New syntax for expressions: `[@ ... ]`
* String syntax: `[@ a = 'word']`
* String concatenation: `[@ myStringVar & 'another string']`
* Rant code interpreted inside strings: `[@ a = '<noun>']`
* Rant code stored as an object: `[@ pattern = $'<verb>']`
* List types are denoted by a list of items: `[@ a = 1, 2, 3, 4, 5, 6, 7]`
* Appending / prepending to lists can be done by placing the items before or after the variable name in a list declaration: `[@ a = 0, a, 8]`
* Access done through bracket notation: `[@ a[3]]`
* Variable scopes. Variables created in blocks are local variables: `{ [@ a = 12] } [@ a] # a does not exist`
* `var` keyword for defining new, empty variables: `[@ var a ] { [@ a = 12] } [@ a] # 12`
* Default value for new variables is "no" (like null or undefined): `[@ var a] [@ a] # no`
* List initializer for initializing empty lists of a given length: `[@ a = list 12; ]` (default values are all no)
* Boolean types. You know the drill: `[@ a = true]`

Thoughts? We'll probably fold the other variable systems into this one once it works and works well.

**Comment by TheBerkin** [comment]
Can we re-implement all of the current [list functions](http://rantlang.github.io/lists.html) as operators in the new expression syntax, too?

**Comment by DaaOtt** [comment]
Ooh, this looks nice. What about type casting?

**Comment by TheBerkin** [comment]
Type casting is currently implicit, like in Javascript. For example, we have different operators for string concatenation (`&`) and addition (`+`), so a cast is not needed for Rant to know which type to return.

**Comment by TheBerkin** [comment]
New list functions:

* Appending (single): `lst +> x;`
* Prepending (single): `lst <+ x;`
* Appending (range): `lst +>> x; # if it's a list, each item is added rather than the list itself`
* Prepending (range): `lst <<+ x;`
* Clearing: `lst!`
* List length: `lst$`
* Remove item at index: `lst[x]!` (returns removed item)
* Remove specified value: `lst?[x]!`
* Get last item: `lst[$]`
* Get index of value: `lst?[x]`
* Run list as pattern: `{@lst}`

**Comment by cpancake** [comment]
We also decided to have a pattern type - like a string, but the contents aren't interpreted on creation. 
* Creation: `[@ pattern = %'<noun>']`
* Execution: `[@ pattern]`

**Comment by DaaOtt** [comment]
Why not just use block syntax for lists (because blocks don't work in expressions)?

**Comment by TheBerkin** [comment]
While blocks and lists can both represent sets of data, they are fundamentally different in what they do:

**Blocks**
* Represent a set of possibilities
* Can only store patterns
* Cannot be indexed
* Items can be weighted
* Immutable, with the exception of targets
* Cannot be resized
* Not actually objects - just a point in the code where the path can diverge.

**Lists**
* Represent a series of objects
* Can store any data type (number, string, pattern...)
* Can be indexed
* Cannot be weighted
* Items are mutable
* Resizable
* Lists can be stored as objects and reused.

The fact that lists can be used as blocks does not mean they are the same thing - it is simply a useful result of their shared characteristics, as well as a convenient way to create and represent blocks from within expressions.
