### ISSUE TITLE
Code won't compile in VS2015 CTP6

### ISSUE THREAD

**Issue by paavohuhtala** [TheBerkin/Rant#47]
The code in this repo won't compile in VS2015 CTP6, because of certain syntax changes in C# 6:

* String interpolation syntax.
  * Old: "I told you about the \\{expression.Here} bro"
  * New: $"I told you about the {expression.Here} bro"
* Using directive with static types
  * Old: using Rant.Engine.Util;
  * New: using static Rant.Engine.Util;

Both of these syntaxes are used heavily in Rant (the compiler reports 300ish syntax errors), but they should be fairly easy to fix, either with regex hackery or a custom tool.

Rant is a \<adj\> library, keep up the \<adj\> work!

**Comment by TheBerkin** [comment]
I was not aware of the syntax change, thanks for letting me know. I've been using the first VS2015 release for all my work so I never had this problem. Looks like it's time for an upgrade and a lot of find/replace...

(I like the *Sweet Bro and Hella Jeff* reference, by the way)

**Comment by TheBerkin** [comment]
Fixed in bbb077624ff85693896daf1cbb7853c050c142ff.
