### ISSUE TITLE
Dictionary syntax improvements

### ISSUE THREAD

**Issue by paavohuhtala** [TheBerkin/Rant#48]
I think the current dictionary syntax could use a few additions.

(samples are not syntax proposals)

## Allow adding already defined words as prefixes/affixes

```
> human/s/ist/esque
> super[^] // -> superhuman/superhumans/superhumanist/superhumanesque
> berry/-ies
> rasp[^] // -> raspberry/raspberries
> straw[^^] // -> strawberry/strawberries
> ball/s
> meat[^]
  | class edible
> basket[^]
  | class sports_equipment

// and / or

> human/s/ist/esque
> berry/-ies
> super[human] -> superhuman/superhumans/superhumanist/superhumanesque
> rasp[berry]
> straw[berry]
> ball/s
> meat[ball]
  | class edible
> basket[ball]
  | class sports_equipment
```
This feature would be extremely useful for languages that use a lot of compound words (like Finnish, Swedish and German).

The second idea is somewhat similar to the first one:

## List & prefix-with directives
```
@list define berries [straw, rasp]

> berry/-ies
@prefix-with berries
```

Once again, definitely more useful for non-English languages. Syntax is just an idea.

Both of these can be accomplised with patterns (especially after #46 is implemented), but I feel like these are good additions to the dictionary syntax to reduce unneeded repetition and the spelling mistakes that come with it.

I can help with the (possible) implementation if needed.

**Comment by paavohuhtala** [comment]
A motivating example in Finnish:
```
@list define talot [parlamentti, eduskunta, maja, ilo]

// The word 'talo' (house) in most of it's grammatical cases
// nominative, plural nominative, genetive, plural genetive, inessive, plural inessive,
// allative, plural allative, illative, plural illative, partitive, plural partitive
// translative, plural translative, essive, plural essive, adessive, plural adessive
// ablative, plural ablative, abessive, plural abessive, comitative, plural comitative
> talo/t/n/jen/ssa/issa/on/ihin/sta/ista/a/ja/ksi/iksi/na/ina/lla/illa/lta/ilta/tta/itta/ineen/ineen

> parlamenttitalo/t/n/jen/ssa/issa/on/ihin/sta/ista/a/ja/ksi/iksi/na/ina/lla/illa/lta/ilta/tta/itta/ineen/ineen
> eduskuntatalo/t/n/jen/ssa/issa/on/ihin/sta/ista/a/ja/ksi/iksi/na/ina/lla/illa/lta/ilta/tta/itta/ineen/ineen
> majatalo/t/n/jen/ssa/issa/on/ihin/sta/ista/a/ja/ksi/iksi/na/ina/lla/illa/lta/ilta/tta/itta/ineen/ineen
> ilotalo/t/n/jen/ssa/issa/on/ihin/sta/ista/a/ja/ksi/iksi/na/ina/lla/illa/lta/ilta/tta/itta/ineen/ineen

// OR

> talo/t/n/jen/ssa/issa/on/ihin/sta/ista/a/ja/ksi/iksi/na/ina/lla/illa/lta/ilta/tta/itta/ineen/ineen
@prefix-with talot
```

And yes, Finnish is weird and unreasonable (although you won't need most of those cases in everyday real-world use).

**Comment by TheBerkin** [comment]
Great ideas! I'll go over these with @cpancake and get his input. I'm especially interested in the cross-entry referencing suggestion you made; it's a useful and clever concept that I would personally get a lot of use out of.

**Comment by cpancake** [comment]
This looks like it would be really useful. The syntax might need to be tweeked a bit but I think the idea is good.

**Comment by paavohuhtala** [comment]
Just a quick update: I went ahead and implemented an initial version of dictionary references on my own. You can take a look at it [here](https://github.com/paavohuhtala/Rant/tree/dict_refs). Feedback is appreciated.

**Comment by TheBerkin** [comment]
I went through your code and checked everything out. Nice work! I like your use of anonymous types in the loader, it's a C# feature I should really take advantage of more often.

I have a few suggestions to make:

**Add the ability to mark table entries used solely as references as "hidden".** This will allow the creation of entry "building blocks" that are not counted by the loader as entries themselves.

**Improve bracket balancing for references.** You currently use a `String.Split` call to look inside bracketed values; the problem with this is that it does not check if the starting/ending brackets are the correct ones. So, for example, I could change `>^ rasp[berry]` to `>^ rasp]berry[` and it still worked:
![Screenshot](http://i.imgur.com/AQWm1EM.png)
This should not be allowed. If you don't want to mess with bracket balancing, you could use a single delimiter token like `%` or `$` instead.

**Increment the minimum required #version for new features.** This prevents programs using older versions of Rant from incorrectly loading tables using a newer version of the format.

Hope this helps.

**Comment by paavohuhtala** [comment]
**Add the ability to mark table entries used solely as references as "hidden".**
Good idea. I will implement this soon.

**Improve bracket balancing for references.**
I've now fixed that by using regex instead of `string.Split`.

**Increment the minimum required #version for new features.**
Okay.
