### ISSUE TITLE
Rave Bytecode

### ISSUE THREAD

**Issue by cpancake** [TheBerkin/Rant#49]
The plan is (or, at least was) for Rave expressions to generate bytecode. We might be able to extend this system in the future to all Rant patterns, making them hella fast and making it easier to write ports (as only the runtime needs to be implemented, instead of the compiler and the runtime). An idea was to base the bytecode on IL bytecode, but with less cryptic opcode names. Does anyone have any other ideas?

**Comment by paavohuhtala** [comment]
A solid idea. I think the best choice is a simple stack-based VM. If the bytecode was similar enough to MSIL, making a Rave-To-MSIL compiler would be very easy, which could improve the performance even further.

**Comment by cpancake** [comment]
Figured out a very simple bytecode format just for expressions. Stack-based.

Operators: 
* `+` - `add`
* `-` - `subtract`
* `*` - `multiply`
* `/` - `divide`
* `%` - `mod`
* `&` - `concat`

Opcodes:
* `push_constant` - `0x00`, 1 argument
* `push_local` - `0x01`, 1 argument
* `push_string` - `0x02`, 1 argument
* `assign` - `0x03`, 1 argument
* `add` - `0x04`, 0 arguments
* `subtract` - `0x05`, 0 arguments
* `multiply` - `0x06`, 0 arguments
* `divide` - `0x07`, 0 arguments
* `mod` - `0x08`, 0 arguments
* `concat` - `0x09`, 0 arguments

Examples:
* `1 + 1` - compiles to `push_constant 2`
* `1 + a` - compiles to `push_constant 1; push_local a; add`
* `a + b` - compiles to `push_local a; push_local b; add`
* `"str" & "str2"` - compiles to `push_string str; push_string str2; concat`
* `a = 1` - compiles to `push_constant 1; assign a`

**Comment by cpancake** [comment]
We might also just figure out the bytecode for the whole language right now. We don't know!

**Comment by TheBerkin** [comment]
Should I set up a new repo to host a markdown file for the bytecode spec? I have a feeling it will be rather large.

**Comment by cpancake** [comment]
If we're going to do it for the entire language that would probably be wise.
