### ISSUE TITLE
Continuous integration?

### ISSUE THREAD

**Issue by paavohuhtala** [TheBerkin/Rant#50]
Both [AppVeyor](http://www.appveyor.com/) and [Travis CI](https://travis-ci.org/) offer free continuous integration for open source projects. While Rant's current test suite is quite small (39 tests at the time of writing), in my opinion automatic unit testing of each commit is helpful in catching bugs and regressions. AppVeyor also supports automatically publishing NuGet packages and nightly builds.

**Comment by TheBerkin** [comment]
Auto-publishing NuGet packages is an idea I can totally get behind! I'll check these out. Thanks!

**Comment by TheBerkin** [comment]
It has been done!
