### ISSUE TITLE
DicLexer performance issues

### ISSUE THREAD

**Issue by TheBerkin** [TheBerkin/Rant#57]
[The last Rantionary build](https://ci.appveyor.com/project/TheBerkin/rantionary/build/1.0.33) took just shy of **23 minutes** because the DIC file lexer is too slow. It seems to be spending the most time on regex matches, so I'd like to have these replaced with manual reading in the lexer rules.

Or just don't use Stringes for the loader. That would be fine, too.

**Comment by cpancake** [comment]
Fixed in e6e730ea9c45aaf1732d6a20f00954868a04f76a.
