### ISSUE TITLE
Queries are really heckin slow.

### ISSUE THREAD

**Issue by cpancake** [TheBerkin/Rant#58]
Queries are right now really slow. We need to come up with ways to speed up queries both for ones with filters and ones on the whole table.

Berkin proposed that we cache the number of entries into each class when loading, and then filter by the smallest class first. I'll implement that soon.

**Comment by TheBerkin** [comment]
Also, cache the weight sums for each class. That will remove the need to recalculate it each time.

**Comment by cpancake** [comment]
Fixed by getting rid of weights. Because nobody uses weights.
