### ISSUE TITLE
Class filter switches give the first listed class priority

### ISSUE THREAD

**Issue by TheBerkin** [TheBerkin/Rant#60]
If I write a query like `<noun-red|yellow|green|blue>`, and it is guaranteed that there are entries with the `red` class, the query will only ever return `red` entries because it doesn't pool the classes' entries into one set. It should have equal probability to filter by any of the four classes, weighted by the relative size of each.

It would, however, be useful to have both behaviors available as options.

**Comment by DaaOtt** [comment]
Sounds reasonable to me, it's only a few characters away from {<noun-red>|<noun-blue>} etc
