### ISSUE TITLE
CSS-style "IMPORT" tag to include external RANT code files

### ISSUE THREAD

**Issue by wflaschka** [TheBerkin/Rant#64]
I've been craving something that would be useful for longer-form procedural generation.

From the commandline, the -file="xxx" argument makes RantConsole.exe use the RANT code stored in a textfile.

I was wondering how possible it would be to reference/include other text files containing RANT code into the code -- *sort of like a CSS import statement.* The imported files could be referenced as either absolute or relative to the current file. 

Ideally, the import procedure would be recursive, permitting the rapid generation of large, widely-varied sets of RANT code from multiple small blocks of imported code. As well, variables defined in an imported piece would be available to the larger generated RANT code as a whole.

Example:

	{
		{
			I'm going to tell you a story.
			|
			Let me share an experience of mine.
		}\n
		{
			[import story/genre/pirate.RANT]
			|
			[import story/genre/romance.RANT]
			|
			[import story/genre/adventure.RANT]
		}
	}

And then one of the story/genre files could subsequently be like:

	#Pirate.RANT
	## Set-up
	{
		[import pirate/character-gen.RANT]
	}
	## Intro and conflict
	{
		[import pirate/intro-type1.RANT]
		|
		[import pirate/intro-type2.RANT]
	}
	## Conflict
	{
		[import pirate/conflict-type1.RANT]
		|[import pirate/conflict-type2.RANT]
		|[import pirate/conflict-type3.RANT]
	}
	## Etc etc

I've been accomplishing this with shell scripts but it's complicated and doesn't reach the power of what a real import method could achieve.

**Comment by TheBerkin** [comment]
This would be simple enough to implement. My main concern would be creating recursion in the VM, but I can probably mitigate that by just loading the final RantAction straight into the VM itself.

**Comment by TheBerkin** [comment]
Added in cc8085c6f5da3ae0105d3ad649f87f41108c4e3b.

**Comment by wflaschka** [comment]
This is my first chance to check in since yesterday morning and... it's added in cc8085c!!? amaze. Thanks, I can't wait to play with it!
