### ISSUE TITLE
RantConsole.exe not seeing arguments

### ISSUE THREAD

**Issue by wflaschka** [TheBerkin/Rant#65]
At some point the RantConsole.exe arguments seem to have stopped working. I updated yesterday to build bc6e279 from a build in late 2014 (that I'd compiled for Mac and didn't want to change).

A command like:

	% RantConsole.exe -file="path-to-pattern-file.rant" -out="out.txt"

simply starts the `RANT>` prompt. Patterns compile properly from the prompt but files passed as arguments have no affect.

I'm running on a Mac under the [Mono Project](http://www.mono-project.com/), but when it didn't work I also tried on Windows 7-Pro 64-bit from command.exe with the same results. 

I'm using [the documentation at http://rantlang.github.io/rantconsole.html](http://rantlang.github.io/rantconsole.html) as my guide. Thanks for any assistance you can give!

**Comment by Spanfile** [comment]
The documentation seems to be outdated. The proper syntax is `RantConsole.exe -file "path-to-pattern-file.rant" -out "out.txt"`

**Comment by wflaschka** [comment]
Thanks @Spanfile! That was very helpful!!
