### ISSUE TITLE
Hidden classes

### ISSUE THREAD

**Issue by TheBerkin** [TheBerkin/Rant#66]
Issue #52 gave me this idea.

Add an option to mark specific dictionary entry classes as "hidden", such that unless a filter is added specifically for that class, hidden entries never show up in query results. This would replace the current `#nsfw` directive and allow for a much broader use of the feature.

Proposed implementation:

Add a `#hidden` header directive that takes a list of class names to hide for that table.
```
#name noun
#subs singular plural
#hidden abstract

> hero/heros
  | class good
> villain/villains
  | class bad
> vice/vices
  | class abstract bad
> virtue/virtues
  | class abstract good
```

Along with this new directive, I would like to also include a new operator, `~`, which includes entries from a hidden class that match the other classes in the current filter.

Using the above table, the following behaviors are possible:

* `<noun>` will return `hero` or `villain`.
* `<noun -good>` will return `hero`.
* `<noun -bad>` will return `villain`.
* `<noun -abstract>` will return `virtue` or `vice`.
* `<noun -abstract -good>` will return `virtue`.
* `<noun -abstract -bad>` will return `vice`.
* `<noun -good~abstract>` will return `hero` or `virtue`.
* `<noun -bad~abstract>` will return `villain` or `vice`.

Of course, I would also like to make it possible to "un-hide" certain classes by means of a constructor overload for `RantDictionary` and/or `RantDictionaryTable` that takes a string array. This would replace the functionality of `NsfwFilter` and allow NSFW entries to be exposed to all queries.

Additionally, it might be a good idea to make the `nsfw` class hidden by default. Certain dictionaries such as [Foulmouth](http://github.com/RantLang/Foulmouth) use a `nsfw` class explicitly and would benefit from this feature.

**Comment by cpancake** [comment]
I like it! We could also have a parameter in RantEngine to unhide entries. That way you could still globally enable NSFW entries.
