### ISSUE TITLE
How long should it take RantEngine to initiate with the Rantionary?

### ISSUE THREAD

**Issue by idvorkin** [TheBerkin/Rant#70]
Code has been running for minutes now, is this expected or am i doing something wrong?

    // cd \gits
    // git clone https://github.com/RantLang/Rantionary

    var n1 = new Rant.RantEngine("c:/gits/Rantionary");
    var o = n1.Do("Hello {noun}");

**Comment by TheBerkin** [comment]
I suspect there are problems with the dictionary table lexer again. In the meantime, loading Rantionary from the .rantpkg file should solve the performance problems. You can find it in the AppVeyor build artifacts for Rantionary.

I'll look into this as soon a I can and see if I can figure out what is causing it to be slow.

**Comment by TheBerkin** [comment]
Hang on a sec... which branch are you cloning from? Should be `dev`.

**Comment by idvorkin** [comment]
A few answers/questions:
1) I'm using nuget for the binary, and RantLang/Rationary for for the dictionary.  
2) How do I find the AppVeyor builds?
3) Is there a nuget package for the dev branch, or should I build myself?

**Comment by TheBerkin** [comment]
Here's a [link](https://ci.appveyor.com/project/TheBerkin/rantionary/build/artifacts) to the latest AppVeyor build artifacts for Rantionary. If you want to find it again, look at the Rantionary README for a green build status icon, and click that.

To use the prerelease (`dev`) build of Rant, use one of the following Package Manager commands:

If you already have Rant installed:
```
PM> Update-Package Rant -Pre
```

If you don't already have Rant installed:
```
PM> Install-Package Rant -Pre
```

**Comment by idvorkin** [comment]
Switching to the pre package fixed it! Thanks!
