### ISSUE TITLE
<noun.plural> returns [Bad Subtype] in sandbox

### ISSUE THREAD

**Issue by factormystic** [TheBerkin/Rant#76]
Specifically, I ran the example code: 

> After <name-male> <verb.ed> [num: 2; 10] <noun.plural>, <name-male> said \"<name-male>, you are a <adj> dude.\"

This was the result:

> After Jerrold despised 9 [Bad Subtype], Wiley said "Bradly, you are a captivating dude."

**Comment by cpancake** [comment]
The .plural subtype was replaced by the .s subtype i.e. `<noun.s>`. We must've left it in the docs from before we changed it.

**Comment by factormystic** [comment]
Oops, I didn't realize github swallowed the rant syntax there. But that sounds like you figured it out.
