### ISSUE TITLE
RantEngine global objects are cleared each time the Sandbox is run

### ISSUE THREAD

**Issue by jmazouri** [TheBerkin/Rant#78]
I'm working on a project that implements Rant with some preset variables, and I noticed that when I tried to set them with RantEngine's indexer, they weren't available in the Rant scripts I ran. Looking further, it seems that the current objects set for a given sandbox is cleared at the start of every run. 

https://github.com/TheBerkin/Rant/blob/ca68f6526610335ab553938c649e780e5910347c/Rant/Engine/Sandbox.cs#L225

I made a quick hack to fix it by replacing that line with this:

    _objects = new ObjectStack(_engine.Objects);

and making _objects not readonly, but there's probably a better way of doing this.

**Comment by TheBerkin** [comment]
Thanks, looking into it now.

**Comment by TheBerkin** [comment]
The global object table was being cleared on every sandbox run, for some odd reason. I've removed the offending line of code and objects persist properly.

There are still some issues being sorted out with list variables not being fetched from the globals, though, so just be aware of that. We'll hopefully have a fix for that soon as well.
