### ISSUE TITLE
Easy way to create long-form text?

### ISSUE THREAD

**Issue by daveaglick** [TheBerkin/Rant#79]
Great project! I'm looking into integration possibilities for my static site generator primarily as a way to spin up placeholder content. I've pretty much got how to create simple strings with dictionary substitutions, but is there an easy/recommended way to generate entire paragraphs of text (or even longer) without relying on some sort of string template? I'm guessing there are ways of doing this with the scripting language, but is there an easier method I've missed?

**Comment by DaaOtt** [comment]
:+1:

The one thing I haven't seen Rant do is generate believable English.

**Comment by cpancake** [comment]
The project that started Rant, "Moist Banana Deluxe", was a long-form text generator. I think it worked by having a bunch of different sentence patterns and choosing randomly from each. Berkin might know of a better way.

Berkin & I were talking about a new project that's more natural language focused and less pattern-based. I don't think it's even past the idea stage yet though.

**Comment by TheBerkin** [comment]
Rant is essentially a templating language at its core, so some usage of templates is practically unavoidable. However, there are ways to generate believable long-form text. The appropriate technique for doing so depends entirely on how detailed the concepts are which you want to communicate through the generated text.

Of course, Rant isn't perfect and it's easier to generate complete nonsense than something that makes sense. I am considering some new features for improving that.

**Comment by daveaglick** [comment]
At least for my case, I'm not too interested in believability (though I can certainly see other use cases where that would be important). Since I'll mainly be using it to generate appropriately sized text for layout and testing purposes, the content can be total nonsense as long as it "looks" like real text (long and short sentences with a mixture of long and short words, good distribution of letters, etc.)

Given that, lets say I want to generate 3 paragraphs with 7 sentences each (of varying lengths). What would be the easiest way to do that? Would I need to write out each paragraphs as a template?

**Comment by TheBerkin** [comment]
In that case, the pattern is quite straightforward. Here's one that uses simple alphabetical nonsense:

```rant
[case:sentence]
[rs:3;\2,N]
{
	[rs:7;\s]
    {
    	[rs:[n:5;16];\s]{[r:[n:1;8]]{\c}}.
    }
}
```
[Sandbox link](http://berkin.me/rant/sandbox#82)

**Comment by daveaglick** [comment]
That is fantastic - exactly what I was looking for. Thanks a lot!
