### ISSUE TITLE
Compiler refactoring

### ISSUE THREAD

**Issue by Spanfile** [TheBerkin/Rant#83]
Currently, the compiler is just a massive switch-clause. It should either be
a) refactored to not be a massive switch-clause or
b) rewritten to not use recursion all over the place.
I don't see why recursion is that bad, but if it has to be done then we'll do it. I'm in favour of option a), so I've thought of some stuff for it.

I'd say the best way to remove the switch-clause is to separate each token handler (or whatever they are called) to their own class or method. The problem with this is that each handler does different things. Some add actions to the final output, some output something straight away, some work together to produce an output. The current implementation is very tightly coupled to the switch-clause, so de-attaching them all from it would basically be rewriting the compiler.

I'm gonna need a hand with this (and possibly a goat). I've got life stuff on the table as well, so rewriting the entire compiler by myself would take a very long time (and multiple goats).

**Comment by cpancake** [comment]
I think it should work like the VM. Berkin's mentioned this in the past and I think it'll probably work well.

The basic idea would be to have a stack of parselets or whatever they're called. To read a query, for example, you'd push the query parselet onto the stack. It would pop the parselet off and call its Run enumerator, which would yield a parselet for the query name, query subtype, query regex, carrier, etc. It would then push the query action onto a result stack.

**Comment by cpancake** [comment]
I guess GitHub doesn't let you assign multiple people to an issue.

**Comment by Spanfile** [comment]
I'll have to look into how the way you mentioned works.

**Comment by Spanfile** [comment]
I've got some free time from school now, so I have actual time to work on stuff. Including rewriting almost 500 lines of code elsewhere and I have no idea where to start. Any guidance? Directions? Goats?

**Comment by cpancake** [comment]
The goal is to have a compiler that:
* Works
* Is maintainable

If you haven't already, I suggest taking a look at the runtime and how that works. That's sort of the same thing I want to do with the compiler.

**Comment by Spanfile** [comment]
I'm pretty sure I see how the VM works it's way around the stacks. The compiler on the other hand is so large, it will take a long time to figure out how it works and then based on that, rewrite the sucker. I've got time, I think.
