### ISSUE TITLE
Emoji support

### ISSUE THREAD

**Issue by TheBerkin** [TheBerkin/Rant#84]
There should be a way to print emojis, possibly with a function. This could be a difficult feature to test, however, without using something that can render emojis.

**Comment by cpancake** [comment]
We could redo RantConsole in Forms to allow it to use other fonts than System (and to add a few more advanced features), which would allow us to support emoji in the console.

**Comment by cpancake** [comment]
What about an emoji dictionary, so you could do something like <emoji-face> or <emoji-animal>? You'd still need some way to return a specific emoji though.

**Comment by TheBerkin** [comment]
Not sure how I'd type them in the file, that's the problem. The idea is cool, sure, but a function would be better. It could just take a mode parameter that specifies the emoji type.

**Comment by cpancake** [comment]
Added in 89cc6aae6edafde1ce6117d2f37a93cb2a99e2dc.
