### ISSUE TITLE
Longer examples of procedural generation?

### ISSUE THREAD

**Issue by wflaschka** [TheBerkin/Rant#9]
This isn't an issue, but I'm a n00b and I couldn't figure out how to contact you directly. I have compiled Rant and I think it's fascinating. **Do you know where I can see longer examples of this language in action?** I.e., an actual script with subroutines and variables, which builds something? Any pointers you can give would be very helpful!!

**Comment by AdamsLair** [comment]
Any update on this? I'd be highly interested in a longer sample as well. Reading the documentation is all good, but it only gets you so far. If there was an example on how to generate, say, a short story in the scale of 2-3 pages, that would be incredibly helpful!

By the way, nice work on the documentation! Looks very polished and overall nicely done :+1:

**Comment by TheBerkin** [comment]
Hello again!

I am working with another developer to introduce some major structural and syntactic improvements to Rant's object model. We are waiting to create any longer examples until after these changes are finalized and implemented. We don't want to have a whole bunch of code become unusable after the update, so we feel that this is the best option right now.

However, I will consider revisiting some of the major topics, like queries, and writing some longer examples using them. I feel like there is a lot more that could be shown than what we currently have.

**Comment by cpancake** [comment]
We do have [best-of-rant](https://github.com/TheBerkin/best-of-rant) right now, but it's far from a complete demonstration of what Rant can do.

**Comment by TheBerkin** [comment]
That repo isn't exactly a "professional" representation of Rant, I might add...
