### ISSUE TITLE
Update the README.md examples

### ISSUE THREAD

**Issue by gl33mer** [TheBerkin/Rant#95]
For example `.plural` has been replaced with `.s` - etc.

**Comment by gl33mer** [comment]
This example also seems broken. (haven't cracked this one yet :) 
`[rhyme:perfect]
The <noun(1)::&a> <verb.ed(1)-transitive::&a> the <adj::&a> <noun(1)::&a>.`

Sometimes gives 1 `[?]` (for 3rd word) - sometimes  2 `[?]` (for 3rd and 5th word) and sometimes  3 `[?]` (for 3rd 5th and 6th word):

for ex:

`The goat [?] the stout throat.`
`The skirt [?] the [?] shirt.`
`The soup [?] the [?] [?].`

**Comment by TheBerkin** [comment]
That's because we don't have enough pronunciation metadata in Rantionary. Not a bug with Rant itself :)

**Comment by gl33mer** [comment]
Ahh. :) on my things to look into then..
