### ISSUE TITLE
Error reopening the file with FileToken 0x00000001 - When compile using .net 3.5

### ISSUE THREAD

**Issue by zappysys** [TheBerkin/Rant#98]

**Comment by cpancake** [comment]
Could you provide a little more information. What build are you using - Debug, Release, Unity? Are you using the unmanaged version? Where is this message displayed - in Visual Studio, when you first run the program, when you call a certain function, or somewhere else?

And how did you manage to get it to build in .NET 3.5? Last time I checked, it wasn't possible to build on anything less than .NET 4.0.

**Comment by zappysys** [comment]
If I use older nuget package it compiles fine with .net 3.5 (I have VS2012 and project has 2 profiles x86, x64)
PM> Install-Package UnmanagedExports -Version 1.2.2.23707
