### ISSUE TITLE
Build fails with Mono on Linux

### ISSUE THREAD

**Issue by Robzz** [TheBerkin/Rant#99]
Disclaimer: I am very new to Mono, and .NET in general. This could totally be a case of me being a puny newbie who didn't do his homework, but to be fair I'm not sure what to search for.

The issue is pretty much in the title, running xbuild with mono fails. I'm running the latest version from the official mono repositories. I tried building both the master and development branches, and both yield the same error. [Here it is](https://gist.github.com/Robzz/8f77a19723f7616141015259108bf4c5) (dev branch)

I saw this line in the README and strongly suspect that this feature is the culprit: 
> Unmanaged function exports for use in C/C++ applications (Windows only, sorry!)

In which case I suppose I can rephrase the issue as "Can I disable the function exports in the build?".

Other than that, congrats on what looks like a cool and fun project! Can't wait to get it running.

**Comment by TheBerkin** [comment]
I am discontinuing the unmanaged exports in Rant 3 to encourage ports of the Rant runtime to other languages directly. This should hopefully solve your issue as well.

**Comment by TheBerkin** [comment]
I just removed all UnmanagedExports-related code and resources. Give the build another try and let me know if you have any further issues.

**Comment by Robzz** [comment]
It works! I'll let Rant do the thanking:

Thank you <adj> much, you <adj>, <adj> <noun>!
Thank you unfortunate much, you proud, Japanese bun!

Oh, I'm gonna like this.
